services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ${PWD}/devel/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/devel/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 1s
      timeout: 3s
      retries: 5
  setup-database:
    image: ghcr.io/semiotic-ai/elric-rs:main
    volumes:
      - ${PWD}/output/schema.sql:/app/schema.sql
    command:
      ["setup", "http://default:default@clickhouse:8123/default", "schema.sql"]
    env_file:
      - .env
    depends_on:
      clickhouse:
        condition: service_healthy

  elric:
    image: ghcr.io/semiotic-ai/elric-rs:sha-1d65466
    volumes:
      - ${PWD}/output/substreams.spkg:/app/substreams.spkg
    command:
      [
        "run",
        "--package-file=/app/substreams.spkg",
        "--start-block=${START_BLOCK}",
        "--end-block=${END_BLOCK}",
        "http://default:default@clickhouse:8123/default?async_insert=1&wait_for_async_insert=0",
        "app",
      ]
    env_file:
      - .env
    depends_on:
      setup-database:
        condition: service_completed_successfully
